#!/usr/bin/env python3
"""
Text to Python Conversion
Generated: 2026-06-30T05:12:23.845Z
Total Lines: 205
"""

def process_text():
    """
    Process and analyze text data
    Returns: dictionary with text data and metadata
    """
    text_lines = [
    "# Economic Indicators Dashboard",
    "# Save this as: economic_dashboard.py",
    "import warnings",
    "warnings.filterwarnings(\"ignore\")",
    "import streamlit as st",
    "import pandas as pd",
    "import numpy as np",
    "import matplotlib.pyplot as plt",
    "import seaborn as sns",
    "from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold",
    "from sklearn.preprocessing import StandardScaler",
    "from sklearn.linear_model import LogisticRegression",
    "from sklearn.tree import DecisionTreeClassifier",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier",
    "from sklearn.metrics import (",
    "    accuracy_score,",
    "    precision_score,",
    "    recall_score,",
    "    f1_score,",
    "    confusion_matrix,",
    "    roc_curve,",
    "    auc,",
    ")",
    "st.set_page_config(",
    "    page_title=\"Economic Indicators Dashboard\",",
    "    page_icon=\"📈\",",
    "    layout=\"wide\",",
    "    initial_sidebar_state=\"expanded\",",
    ")",
    "st.markdown(",
    "    \"\"\"",
    "    <style>",
    "    .main-header {",
    "        font-size: 42px;",
    "        font-weight: bold;",
    "        color: white;",
    "        text-align: center;",
    "        padding: 20px;",
    "        background: linear-gradient(90deg, #2c3e50 0%, #4ca1af 100%);",
    "        border-radius: 10px;",
    "    }",
    "    .sub-header {",
    "        font-size: 24px;",
    "        font-weight: bold;",
    "        color: #2c3e50;",
    "        padding: 10px 0;",
    "        border-bottom: 3px solid #4ca1af;",
    "        margin-bottom: 15px;",
    "    }",
    "    .finding-box {",
    "        background: #fff3cd;",
    "        border: 1px solid #ffc107;",
    "        border-radius: 8px;",
    "        padding: 15px;",
    "        margin: 10px 0;",
    "    }",
    "    .recommendation {",
    "        background: #d4edda;",
    "        border: 1px solid #28a745;",
    "        border-radius: 8px;",
    "        padding: 15px;",
    "        margin: 10px 0;",
    "    }",
    "    .alert-box {",
    "        background: #f8d7da;",
    "        border: 1px solid #dc3545;",
    "        border-radius: 8px;",
    "        padding: 15px;",
    "        margin: 10px 0;",
    "        color: #721c24;",
    "    }",
    "    </style>",
    "    \"\"\",",
    "    unsafe_allow_html=True,",
    ")",
    "@st.cache_data",
    "def load_data():",
    "    df = None",
    "    for path in [\"data/economic_data.csv\", \"economic_data.csv\"]:",
    "        try:",
    "            df = pd.read_csv(path)",
    "            break",
    "        except FileNotFoundError:",
    "            continue",
    "    if df is None:",
    "        dates = pd.date_range(\"2015-01-01\", periods=120, freq=\"M\")",
    "        rng = np.random.default_rng(42)",
    "        df = pd.DataFrame(",
    "            {",
    "                \"date\": dates,",
    "                \"gdp_growth\": rng.normal(2.5, 1.2, len(dates)),",
    "                \"inflation_rate\": rng.normal(3.0, 1.0, len(dates)),",
    "                \"unemployment_rate\": rng.normal(6.0, 1.5, len(dates)),",
    "                \"interest_rate\": rng.normal(4.0, 1.0, len(dates)),",
    "                \"consumer_spending_growth\": rng.normal(2.2, 1.1, len(dates)),",
    "                \"industrial_production_growth\": rng.normal(2.8, 1.3, len(dates)),",
    "                \"trade_balance\": rng.normal(-1.5, 0.8, len(dates)),",
    "                \"stock_index_return\": rng.normal(0.8, 2.5, len(dates)),",
    "            }",
    "        )",
    "    if \"date\" not in df.columns:",
    "        for c in [\"Date\", \"month\", \"period\"]:",
    "            if c in df.columns:",
    "                df = df.rename(columns={c: \"date\"})",
    "                break",
    "    df[\"date\"] = pd.to_datetime(df[\"date\"], errors=\"coerce\")",
    "    df = df.sort_values(\"date\").reset_index(drop=True)",
    "    return df",
    "@st.cache_data",
    "def build_features(df):",
    "    d = df.copy()",
    "    if \"gdp_growth\" in d.columns and \"inflation_rate\" in d.columns:",
    "        d[\"real_growth_proxy\"] = d[\"gdp_growth\"] - d[\"inflation_rate\"] * 0.2",
    "    if \"consumer_spending_growth\" in d.columns and \"industrial_production_growth\" in d.columns:",
    "        d[\"economic_activity_index\"] = (",
    "            d[\"consumer_spending_growth\"].fillna(0) * 0.5",
    "            + d[\"industrial_production_growth\"].fillna(0) * 0.5",
    "        )",
    "    if \"unemployment_rate\" in d.columns:",
    "        d[\"labor_stress_index\"] = d[\"unemployment_rate\"] / (d[\"unemployment_rate\"].mean() + 1e-6)",
    "    if \"interest_rate\" in d.columns and \"inflation_rate\" in d.columns:",
    "        d[\"policy_gap\"] = d[\"interest_rate\"] - d[\"inflation_rate\"]",
    "    return d",
    "@st.cache_data",
    "def train_models(df):",
    "    d = build_features(df)",
    "    if \"growth_class\" in d.columns:",
    "        target = \"growth_class\"",
    "    elif \"recession_flag\" in d.columns:",
    "        target = \"recession_flag\"",
    "    elif \"inflation_flag\" in d.columns:",
    "        target = \"inflation_flag\"",
    "    else:",
    "        base = d[\"gdp_growth\"] if \"gdp_growth\" in d.columns else pd.Series([0] * len(d))",
    "        d[\"target\"] = (base > base.median()).astype(int)",
    "        target = \"target\"",
    "    y = d[target].astype(int)",
    "    feature_cols = [",
    "        c for c in d.columns",
    "        if c not in [\"date\", target] and pd.api.types.is_numeric_dtype(d[c])",
    "    ]",
    "    X = d[feature_cols].copy().fillna(d[feature_cols].median(numeric_only=True))",
    "    if len(X) < 20 or y.nunique() < 2:",
    "        return {}, X, y, target",
    "    X_train, X_test, y_train, y_test = train_test_split(",
    "        X, y, test_size=0.25, random_state=42, stratify=y",
    "    )",
    "    scaler = StandardScaler()",
    "    X_train_scaled = scaler.fit_transform(X_train)",
    "    X_test_scaled = scaler.transform(X_test)",
    "    models = {",
    "        \"Logistic Regression\": LogisticRegression(max_iter=2000),",
    "        \"Decision Tree\": DecisionTreeClassifier(max_depth=6, random_state=42),",
    "        \"Random Forest\": RandomForestClassifier(n_estimators=200, random_state=42),",
    "        \"Gradient Boosting\": GradientBoostingClassifier(random_state=42),",
    "    }",
    "    results = {}",
    "    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)",
    "    for name, model in models.items():",
    "        use_scaled = name == \"Logistic Regression\"",
    "        Xtr = X_train_scaled if use_scaled else X_train",
    "        Xte = X_test_scaled if use_scaled else X_test",
    "        model.fit(Xtr, y_train)",
    "        y_pred = model.predict(Xte)",
    "        y_prob = model.predict_proba(Xte)[:, 1] if hasattr(model, \"predict_proba\") else model.decision_function(Xte)",
    "        cv_scores = cross_val_score(model, Xtr, y_train, cv=cv, scoring=\"accuracy\")",
    "        fpr, tpr, _ = roc_curve(y_test, y_prob)",
    "        results[name] = {",
    "            \"model\": model,",
    "            \"accuracy\": accuracy_score(y_test, y_pred),",
    "            \"precision\": precision_score(y_test, y_pred, zero_division=0),",
    "            \"recall\": recall_score(y_test, y_pred, zero_division=0),",
    "            \"f1\": f1_score(y_test, y_pred, zero_division=0),",
    "            \"cv_mean\": cv_scores.mean(),",
    "            \"cv_std\": cv_scores.std(),",
    "            \"fpr\": fpr,",
    "            \"tpr\": tpr,",
    "            \"roc_auc\": auc(fpr, tpr),",
    "            \"cm\": confusion_matrix(y_test, y_pred),",
    "        }",
    "    return results, X, y, target",
    "def main():",
    "    st.markdown('<div class=\"main-header\">Economic Indicators Dashboard</div>', unsafe_allow_html=True)",
    "    df = load_data()",
    "    df = build_features(df)",
    "    results, X, y, target = train_models(df)",
    "    st.sidebar.title(\"Navigation\")",
    "    page = st.sidebar.radio(",
    "        \"Select Analysis Module\",",
    "        [",
    "            \"Executive Summary\",",
    "            \"Trend Analysis\",",
    "            \"Correlation Analysis\",",
    "            \"ML Models\",",
    "            \"ROC Curves\",",
    "            \"Confusion Matrices\",",
    "            \"Findings & Recommendations\",",
    "        ],",
    "    )",
    "    st.sidebar.markdown(\"---\")",
    "    st.sidebar.info(",
    "        f\"Records: {len(df)}\\n\"",
    "        f\"Numeric Variables: {len(df.select_dtypes(include=np.number).columns)}\"",
    "    )",
    "    if page == \"Executive Summary\":"
    ]
    
    # Calculate metadata
    metadata = {
        'total_lines': 205,
        'total_characters': 7331,
        'total_words': 616,
        'created_at': '2026-06-30T05:12:23.845Z',
        'version': '1.0'
    }
    
    # Calculate statistics
    line_lengths = [len(line) for line in text_lines]
    statistics = {
        'average_line_length': sum(line_lengths) // len(line_lengths) if line_lengths else 0,
        'longest_line': max(line_lengths) if line_lengths else 0,
        'shortest_line': min(line_lengths) if line_lengths else 0,
        'empty_lines': 33
    }
    
    return {
        'lines': text_lines,
        'metadata': metadata,
        'statistics': statistics
    }

def display_text(data):
    """Display text data with metadata"""
    print("Metadata:")
    for key, value in data['metadata'].items():
        print(f"  {key}: {value}")
    
    print("\nStatistics:")
    for key, value in data['statistics'].items():
        print(f"  {key}: {value}")
    
    print("\nText Lines:")
    for i, line in enumerate(data['lines'], 1):
        print(f"Line {i}: {line}")

if __name__ == "__main__":
    data = process_text()
    display_text(data)